### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by TheAugoosetus** [MeltyPlayer/MeltyTool#10]
Hello! I'm relatively new to all of this, so I could have made a mistake, but I downloaded the code from the main page as instructed, converted my Pikmin 2's .nkit.iso to an .iso format, put it in the /roms folder, and renamed it to pikmin_2.gcm. When I ran rip_pikmin_2, this is what it told me. 

C:\Users\okaug\Desktop\Pikmin PIA\Tools\Fin Model Utility\cli>tools\universal_model_extractor\universal_model_extractor.exe pikmin_2
Unhandled exception. System.Exception: Expected to find file: 'pikmin_2.gcm' in directory 'C:\Users\okaug\Desktop\Pikmin PIA\Tools\Fin Model Utility\cli\roms'
   at fin.io.FinDirectory.GetExistingFile(String path)
   at fin.io.FinDirectory.PossiblyAssertExistingFile(String relativePath, Boolean assert)
   at uni.games.pikmin_2.Pikmin2FileGatherer.GatherFileBundles(Boolean assert)
   at uni.games.ExtractorUtil.ExtractAll[T](IFileBundleGatherer`1 gatherer, IModelLoader`1 loader)
   at uni.games.pikmin_2.Pikmin2Extractor.ExtractAll()
   at uni.cli.Cli.<>c.<Main>b__0_13(Pikmin2Options _)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at uni.cli.Cli.Main(String[] args).

When I ran launch_ui instead, it opened the universal model extractor program and my command prompt, which read
C:\Users\okaug\Desktop\Pikmin PIA\Tools\FinModelUtility-main\cli>tools\universal_model_extractor\universal_model_extractor.exe ui

It stayed like this for about twenty minutes before I had to go somewhere and I shut off my computer. 

EDIT: Today, I noticed that there was an update on the github main page for this project, so I deleted my previous copy, reinstalled the program, and I moved my Pikmin 2 rom to the /roms folder. In it, the README said to name the file pkmn2.gcm instead of pikmin_2.gcm, which I have done and am currently in the same wait cycle mentioned above from running lauch_ui. I will update this when/if there is a change.

**Comment by TheAugoosetus** [comment]
Additionally, the README in the \roms folder states that Pikmin 2 is the only supported game and says to name Pikmin 2 as pkmn2.gcm, but the README in the \FinModelUtility-main folder states that Double Dash, Sunshine, Battalion Wars, and more are all supported and to name Pikmin 2 as pikmin_2.gcm

**Comment by TheAugoosetus** [comment]
This has been my view for over three hours now ![image](https://user-images.githubusercontent.com/120234691/206876010-2a24d922-9cef-4fa5-9388-3ea4c39e3c03.png)

**Comment by TheAugoosetus** [comment]
Three hours later, this is all that has changed.
![IMG_1605](https://user-images.githubusercontent.com/120234691/206876101-1f836a2e-ff44-4dfd-a18f-9d3844d3a609.png)

**Comment by TheAugoosetus** [comment]
Hello, all! I talked with MeltyPlayer, and we found the issue! I simply didn't have file extensions shown, so when I was naming the file `pikmin_2.gcm`, I was really naming it `pikmin_2.gcm.iso`. While embarrassing, I'll leave this up in case anyone else has the same issue that I did.
