### ISSUE TITLE
Getting an Unhandled Exception when trying to dump Majora's Mask even after installing the HackingToolkit

### ISSUE THREAD

**Issue by NickaNak** [MeltyPlayer/MeltyTool#14]
As the title says I'm getting an Unhandled Exception when ever I try to extract Majora's Mask, I've got the hacking toolkit which auto installed in my c drive for some reason and I've also tried coping the files from that folder in the c drive, into the HackingToolkit9DSv12 folder that's inside FniModelUtilitie's tools folder, both give me the same issue

I've got my majora's mask rom in the correct folder and named correctly too "majoras_mask_3d.cia"

I can paste the Unhandled Exception log when I get the Unhandled Exception if that's helpful

**Comment by NickaNak** [comment]
Oh yeah sorry I just want to add, I've downloaded the tool from the Green "Code" Button >> Download Zip on your main repo page, I saw mention of that (from other issues) that it's the best way to download the tool

**Comment by MeltyPlayer** [comment]
I've switched from using HackingToolkit9DS to Ctrtool for extracting CIAs, could you give this another try?

**Comment by NickaNak** [comment]
Will give it a go!

**Comment by NickaNak** [comment]
Unfortunately it's still not working for me
The launch UI bat file gives me this error
```
F:\Extracting Models\FinModelUtility\cli>tools\universal_model_extractor\universal_model_extractor.exe ui
Dumping ROM F:\Extracting Models\FinModelUtility\cli\roms\majoras_mask_3d.cia...
fin.util.asserts.AssertionException: Failed to find expected ROM filesystem output directory. There may be something with the following CIA: F:\Extracting Models\FinModelUtility\cli\roms\majoras_mask_3d.cia
   at uni.platforms.threeDs.tools.CtrtoolCiaExtractor.Run(ISystemFile romFile, IFileHierarchy& hierarchy)
   at uni.platforms.threeDs.ThreeDsFileHierarchyExtractor.ExtractFromRom(ISystemFile romFile, ISet`1 junkTerms)
   at uni.games.majoras_mask_3d.MajorasMask3dFileGatherer.GatherFileBundles(Boolean assert)
   at fin.io.bundles.IFileBundleGatherer`1.fin.io.bundles.IFileBundleGatherer.GatherFileBundles(Boolean assert)
   at fin.io.bundles.ParallelFileBundleGathererAccumulator.GathererRunner.Invoke(Int32 i)

```
The GUI loads after this error but there's no models extracted

The error mentions the rom being incorrect, I'm Honestly not sure if the rom is ok, It's the same one I was using before I haven't decrypted it or done anything with it

**Comment by MeltyPlayer** [comment]
Thanks for giving it a try, sorry it’s still not working.

That’s just the generic error I put for when it doesn’t work, it just means that the contents weren’t extracted.

Could you calculate the hashes for your ROM with this website and share them here?
https://md5file.com/calculator

**Comment by NickaNak** [comment]
Sure thing
Here's all the Hashes

MD5: 48583765fbffa1708d4e3aa23d338a45
SHA1: 6a5bec986f5161310837fe5f47ff80045f68cba5
SHA256: c1a51c3791baaa616c08f01d9fcba0f8058a908cbc5d19f94f5fca380b5f63b3
SHA512: 07052ea29d021a26aa8391ffb0c6451d5475996fb6597579a688dd0bd77bae28894487619e7629fabccfc3a38e5f80e7fad38a04b53bf78534b667ff418fcb02

**Comment by NickaNak** [comment]
I came back to this issue and tried something, I had your model extractor in a folder with a space in it's name, I took it out of that location and ran your tool again and it worked, so I'm guessing the space in a folder name in the path to the universal_model_extractor/universal_model_tool was creating the issues
