### ISSUE TITLE
Super Mario Sunshine - Error loading unmanaged library from path: assimp.dll

### ISSUE THREAD

**Issue by dogcreature** [MeltyPlayer/MeltyTool#16]
When attempting to export the /data/scene/mare0/map/map/map file from Super Mario Sunshine it outputs a .glb file (The .glb appears to work just fine) and throws the following error in the console:

```
D:\Users\Nisha\Downloads\FinModelUtility-main(3)\FinModelUtility-main\cli>tools\universal_model_extractor\universal_model_extractor.exe ui
Extracting model \data\scene\mare0\map\map\map.bmd
Writing to D:\Users\Nisha\Downloads\FinModelUtility-main(3)\FinModelUtility-main\cli\out\super_mario_sunshine\data\scene\mare0\map\map\map\map.tmp.glb...
Assimp.AssimpException: Error loading unmanaged library from path: assimp.dll

The specified module could not be found. (0x8007007E)
 ---> System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   --- End of inner exception stack trace ---
   at Assimp.Unmanaged.UnmanagedLibrary.UnmanagedWindowsLibraryImplementation.NativeLoadLibrary(String path)
   at Assimp.Unmanaged.UnmanagedLibrary.UnmanagedLibraryImplementation.LoadLibrary(String path)
   at Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary(String libPath)
   at Assimp.Unmanaged.UnmanagedLibrary.LoadLibrary()
   at Assimp.Unmanaged.UnmanagedLibrary.LoadIfNotLoaded()
   at Assimp.Unmanaged.AssimpLibrary.GetExportFormatDescriptions()
   at Assimp.AssimpContext.QueryExportFormatsIfNecessary()
   at Assimp.AssimpContext.GetSupportedExportFormats()
   at fin.exporter.assimp.indirect.AssimpIndirectExporter.Export(IFile outputFile, String[] exportedFormats, IModel model)
   at uni.games.ExtractorUtil.Extract[T](T modelFileBundle, Func`1 loaderHandler)
```

I am running this on Windows 11.

**Comment by MeltyPlayer** [comment]
I'm not sure what would have caused this issue at the time, but hopefully this should all be working now!
