### ISSUE TITLE
Fix how the ROMs directory is found relative to the EXE

### ISSUE THREAD

**Issue by ghost** [MeltyPlayer/MeltyTool#2]
Howdy, I got a US Mario Sunshine rom in the roms folder with the correct name and format and I get the following error when trying to run the rip_super_mario_sunshine batch file, I've tried with both builds from the releases tab and from the code button.

**G:\Programs\FinModelUtility v0.2>tools\universal_model_extractor\universal_model_extractor.exe super_mario_sunshine
Unhandled exception. System.TypeInitializationException: The type initializer for 'uni.platforms.DirectoryConstants' threw an exception.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at uni.platforms.DirectoryConstants..cctor() in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\UniversalModelExtractor\src\platforms\DirectoryConstants.cs:line 8
   --- End of inner exception stack trace ---
   at uni.games.super_mario_sunshine.SuperMarioSunshineExtractor.ExtractAll() in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\UniversalModelExtractor\src\games\super_mario_sunshine\SuperMarioSunshineExtractor.cs:line 22
   at uni.cli.Cli.<>c.<Main>b__0_11(SuperMarioSunshineOptions _) in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\UniversalModelExtractor\src\cli\Cli.cs:line 77
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at uni.cli.Cli.Main(String[] args) in R:\Documents\CSharpWorkspace\Pikmin2Utility\FinModelUtility\UniversalModelExtractor\src\cli\Cli.cs:line 26

G:\Programs\FinModelUtility v0.2>pause**

**Comment by MeltyPlayer** [comment]
Hello, thanks for filing this bug! This is a known issue with version 0.2—can you try downloading the project via the green button and “Download ZIP” option in the “Code” tab instead?

**Comment by ghost** [comment]
Hello, you caught me just as I was about to edit the issue to mention the fact that I've tried both builds from Releases and the Code button ^^

**Comment by ghost** [comment]
I've got it working now, I originally tried v0.2 then downloaded the project and just overwrited the v0.2 files, this time I extracted to it's own folder. So it was just me being a bit silly lol.

Thank you for taking the time to respond ^^

**Comment by MeltyPlayer** [comment]
No problem, glad you got it working!
